### ISSUE TITLE
onChange does not return any value

### ISSUE THREAD

**Issue by christiangrieger** [slawomir-zaziablo/range-slider#6]
Hey, i tried to use this slider but the onChange function seems to not fire?

<img width="375" alt="Bildschirmfoto 2020-12-20 um 11 38 18" src="https://user-images.githubusercontent.com/8712219/102711169-fb730680-42b7-11eb-8101-a0644a9f74db.png">

The slider itself does display the right way:

<img width="1349" alt="Bildschirmfoto 2020-12-20 um 11 39 30" src="https://user-images.githubusercontent.com/8712219/102711180-09288c00-42b8-11eb-8bcd-e279af0a1f26.png">

Any idea?

Greetings,
Chris

**Comment by christiangrieger** [comment]
Okay i found out how to use the onChange :)

**Comment by rixx** [comment]
How did you do it in the end? I'm running into the same issue here …

Edit: For future reference, you're not meant to call `.onChange()` on the slider object, you're meant to pass it during initialisation, like this:

```js
  const reviewSlider = new rSlider({
          target: '#reviewSlider',
          values: Array(max + 1).fill().map((element, index) => index),
          range: true,
          tooltip: false,
          scale: true,
          labels: true,
          width: "270px",
          set: [parseInt(minInitial), parseInt(maxInitial)],
          onChange: (values) => {
            console.log(values)
          }
      });
```

**Comment by christiangrieger** [comment]
I had placed onChange at the wrong position. This is my working solution:

```
    var rangeSlider = new rSlider({
        target: '#rangeSlider',
        values: [0, 1, 2, 5, 10, 30, 50],
        range: true,
        tooltip: false,
        scale: true,
        labels: true,
        set: [0, 50],
        onChange: function (vals) {
            let sliderValues = vals.split(',');
            tableMinPrice = sliderValues[0];
            tableMaxPrice = sliderValues[1];
            createTable();
        }
    });
```
